django_housingmap/HeatMap/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('HeatMap.views',
	url(r'^getHousingGrowthinBoundingbox.json$', 'price_growth_in_bounding_box_to_geojson', name ='price_growth_in_bounding_box_to_geojson'),
	url(r'^getHousingGrowthinBoundingboxTestForm.html$','price_growth_in_bounding_box_to_geojson_form'),
	url(r'^ZipCodeTest.html$', 'zip_code_test'),
	url(r'^GeoJSON.js$','geojson_js_parser'),
        url(r'', 'home')
) 


#urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'framework.views.home', name='home'),
    # url(r'^framework/', include('framework.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
#)

django_housingmap/framework/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^home/', include('HeatMap.urls', namespace = 'HeatMap')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'framework.views.home', name='home'),
    # url(r'^framework/', include('framework.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
#)

django_housingmap/templates/BoxTest.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
{% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}

<form action="{% url 'HeatMap:price_growth_in_bounding_box_to_geojson' %}" method ='GET'>
	<label for="westLongitude">West Longitude:</label>
	<input type="text" name="westLongitude" id="westLongitude" value="{{westLongitude}}"/><br/>
	
	<label for="eastLongitude">East Longitude:</label>
	<input type="text" name="eastLongitude" id="eastLongitude" value="{{eastLongitude}}"/><br/>
	
	<label for="northLatitude">North Latitude:</label>
	<input type="text" name="northLatitude" id="northLatitude" value="{{northLatitude}}"/><br/>
	
	<label for="southLatitude">South Latitude:</label>
	<input type="text" name="southLatitude" id="southLatitude" value="{{southLatitude}}"/><br/>
	
	<label for="input_year1">Year1: </label>
	<input type="text" id="input_year1" name="input_year1"/><br/>
					
	<label for="input_year2">Year2: </label>
	<input type="text" id="input_year2" name="input_year2"/><br/>
					
	<input type="submit" value="submit"/>
</form>
</body>
</html>

django_housingmap/templates/ZipCodeTest.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		html { height: 100% }
		body {height: 100%; margin: 0; padding: 0 }
		#map-canvas { height: 100%; width:80%; float:right;}
		#side-panel{height: 100%; width:20%; overflow:auto; float:left;}
	</style>
	<script type="text/javascript" 
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA_JEN1JLQ2C341o4pAuyd04GSYd-Q89Lg&libraries=drawing&sensor=false">
	</script>
	<script type="text/javascript"
		src="/home/GeoJSON.js">
	</script>
	<script type="text/javascript">
	function initialize() {		
		//Map Information
		  var myLatLng = new google.maps.LatLng(37.42291810, -122.08542120);
		  var mapOptions = {
		    zoom: 10,
		    center: myLatLng,
		    mapTypeId: google.maps.MapTypeId.TERRAIN
		  };

		  var map = new google.maps.Map(document.getElementById("map-canvas"),
		      mapOptions);		
		var googleMapsVector={};
		
		var polygonRequest = new XMLHttpRequest();
		polygonRequest.onload = function() {
				//	document.getElementById('debug').innerHTML += "Recieved JSON<br>";
					var response = this.responseText;
					//document.getElementById('debug').innerHTML += response;
					var result = JSON.parse(response);
			
					var shapeOptions = {
  						strokeColor: "rgb(255,0,0)",
		    			strokeOpacity: 0.8,
		    			strokeWeight: 2,
		    			fillColor: "rgb(255,0,0)",
		    			fillOpacity: 0.35
					};
					
					// remove existing shapes: overlapping shapes increase opacity
					for(var i = 0; i < googleMapsVector.length; i++){
						for (var j = 0; j <googleMapsVector[i].length; j++){
							googleMapsVector[i][j].setMap(null);
						}
					}
					
					// get google map shapes from results
					googleMapsVector = new GeoJSON(result, shapeOptions);
														
          //standard deviation: sqrt((sum (val - avg)^2) / n)
          //calculate average 
          var avg = 0;
          var total_len = 0
					for(var i = 0; i < googleMapsVector.length; i++){
						for (var j = 0; j <googleMapsVector[i].length; j++){
							avg = avg + googleMapsVector[i][j].geojsonProperties.value;
            }
            total_len = total_len + googleMapsVector[i].length;
          }
          avg = avg/total_len;

          var sum = 0;
          for(var i = 0; i < googleMapsVector.length; i++){
						for (var j = 0; j <googleMapsVector[i].length; j++){
              sum = sum + Math.pow(googleMapsVector[i].length - avg, 2);
            }
          }
          var scale = Math.sqrt(sum/total_len);

					// assign the shapes to map
					for(var i = 0; i < googleMapsVector.length; i++){
						for (var j = 0; j <googleMapsVector[i].length; j++){
              var val = googleMapsVector[i][j].geojsonProperties.value;
              var temp_scale = scale;
              var heat = 0;
              var color = "rgb("+(255)+","+(0)+",0)";

              while (temp_scale < val) {
                temp_scale = temp_scale * 1.2;
                heat = heat + 1;
              }

              if (heat < 1) {
                color = "rgb("+(0)+","+(255)+",255)";
              }
              else if (heat < 2) {
                color = "rgb("+(0)+","+(255)+",0)";
              }
              else if (heat < 3) {
                color = "rgb("+(255)+","+(0)+",255)";
              }

              if (val < 0) {
                color = "rgb("+(255)+","+(255)+",255)";
              }

							googleMapsVector[i][j].setOptions({
								strokeColor: color,
								fillColor: color});
              googleMapsVector[i][j].setMap(map);
            
						}
					}
				};
		
		google.maps.event.addListener(map,'idle', function(){		
		  	//	document.getElementById('debug').innerHTML += "Idle<br>";
				// asynchronous json request      
				//document.getElementById('debug').innerHTML += "Fetching JSON<br>";
				
				var westLongitude = map.getBounds().getSouthWest().lng();
				var southLatitude = map.getBounds().getSouthWest().lat();
				var eastLongitude = map.getBounds().getNorthEast().lng();
				var northLatitude = map.getBounds().getNorthEast().lng();
				
				//document.getElementById('debug').innerHTML += 
					'Polygon((' + westLongitude + ' ' + southLatitude + ',' 
						+ westLongitude + ' ' + northLatitude + ','
						+ eastLongitude + ' ' + northLatitude + ','
						+ eastLongitude + ' ' + southLatitude + ','
						+ westLongitude + ' ' + southLatitude + '))' + '<br>';
				
				// abort the previous request
				// prevents loading the wrong set of polygons
				// ! may or may not stop django's db request.
				var year1 = $( "#slider-range" ).slider( "values", 0 );
				var year2 = $( "#slider-range" ).slider( "values", 1 );
				polygonRequest.abort();
				//*
				var GETstring ="?westLongitude="+map.getBounds().getSouthWest().lng()
					+"&eastLongitude="+map.getBounds().getNorthEast().lng()
					+"&northLatitude="+map.getBounds().getNorthEast().lat()
					+"&southLatitude="+map.getBounds().getSouthWest().lng()
					+"&year1="+year1
					+"&year2="+year2;
				//*/
				
			//	document.getElementById('debug').innerHTML+= GETstring + '<br>';
				
				polygonRequest.open("GET", "{% url 'HeatMap:price_growth_in_bounding_box_to_geojson' %}" + GETstring, true);
				polygonRequest.send();
				/*
				var myForm = new FormData();
				myForm.append('northLatitude',map.getBounds().getNorthEast().lat());
				myForm.append('southLatitude',map.getBounds().getSouthWest().lat());
				myForm.append('westLongitude',map.getBounds().getSouthWest().lng());
				myForm.append('eastLongitude',map.getBounds().getNorthEast().lng());
				xhr.send(myForm);
				//*/
		  	});
	}
		function goButton(){
      initialize();
		}

	google.maps.event.addDomListener(window,'load',initialize);
	</script>
</head>
<body>

	{% include 'navbar2.html' %}

		<div id="side-panel">
		{% include 'slider.html' %}
			<form style="left:50px">
				<fieldset>
					<input type="button" value="Go!" onclick="goButton()"/>

				</fieldset>
			</form>
			{% include 'legend.html' %}
			<br>
			<div id="debug">
			</div>

		</div>
		<div id="map-canvas">this is the map</div>
</body>
</html>

django_housingmap/templates/legend.html
<table>
  <tr>
    <th>Color</th>
    <th>Percent Growth</th>
  </tr>
  <tr>
    <td><font color="Red">Red</font></td>
    <td> > 90%</td>
  </tr>
  <tr>
    <td><font color="FF00FF">Purple</font></td>
    <td>60% - 90%</td>
  </tr>
  <tr>
    <td><font color="00FF00">Green</font></td>
    <td>30% - 60%</td>
  </tr>
  <tr>
    <td><font color="00FFFF">Turquoise</font></td>
    <td>0% - 30%</td>
  </tr>
  <tr>
    <td>White</td>
    <td> < 0%</td>
  </tr>
</table>

django_housingmap/templates/navbar2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Housing Heat Map</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="http://getbootstrap.com/2.3.2/assets/ico/favicon.png">
 


	<!-- core to include the highcharts and jQuery libraries goes here -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="http://code.highcharts.com/highcharts.js"></script>		
  


 </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/home/ZipCodeTest.html">Housing Heat Map</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/home/Chart/">Charts</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://getbootstrap.com/2.3.2/assets/js/jquery.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-transition.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-alert.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-modal.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-dropdown.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-scrollspy.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-tab.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-tooltip.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-popover.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-button.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-collapse.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-carousel.js"></script>
    <script src="http://getbootstrap.com/2.3.2/assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

django_housingmap/templates/results.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- load_charts filter takes a comma-separated list of id's where -->
    <!-- the charts need to be rendered to                             -->
    {% load chartit %}
  </head>

  <body>

      {% include 'navbar2.html' %}	

      <h1>Housing Price Trends</h1>
      <form action method="get">
	 Enter ZipCode: <input type="text" name="zip" value=""><input type="submit" value="Go">
      </form>
      <div id="house_container"> 
         {{housedata|load_charts:"house_container"}}
      </div>
	
  </body>
</html>



django_housingmap/templates/resultsTest.html
<!DOCTYPE html>
<html lang="en">

  <head>
  	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{STATIC_URL}}/static/assets/ico/favicon.png" >

    <title>Housing HeatMap</title>

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}/static/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}/static/examples/starter-template/starter-template.css" rel="stylesheet">
	<!-- Le styles -->
    <link href="{{STATIC_URL}}/static/assets/css/bootstrap.css" rel="stylesheet">
    <link href="{{STATIC_URL}}/static/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{STATIC_URL}}/static/assets/css/docs.css" rel="stylesheet">
    <link href="{{STATIC_URL}}/static/assets/js/google-code-prettify/prettify.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}/static/assets/js/html5shiv.js"></script>
      <script src="{{STATIC_URL}}/static/assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Housing Heat Map</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="starter-template">
        <h1>Housing Heat Map</h1>
        <p class="lead">Enter the Following:</p>
      </div>
	
	<ul class="nav nav-pills">
              <li class="dropdown">
                <a class="dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">From <b class="caret"></b></a>
                <ul id="menu2" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1997</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1998</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1999</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2000</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2001</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2002</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2003</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2004</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2005</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2006</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2007</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2008</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2009</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2010</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2011</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2012</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2013</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a class="dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">To <b class="caret"></b></a>
                <ul id="menu3" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1997</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1998</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">1999</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2000</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2001</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2002</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2003</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2004</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2005</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2006</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2007</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2008</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2009</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2010</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2011</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2012</a></li>
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#">2013</a></li>
                </ul>
              </li>
            <div class="bs-docs-example" style="padding-bottom: 24px;">
              <button type="button" id="fat-btn" data-loading-text="loading..." class="btn btn-primary">
                Go!
              </button>
            </div>
            
            </ul>
	
	

	
	{% for h in house %}
	{{ h.house_date }}
	${{ h.house_price }}
	{{ h.house_zip }}<br>
	{% endfor %}
	
    </div><!-- /.container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="{{STATIC_URL}}/static/text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/jquery.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-transition.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-alert.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-modal.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-dropdown.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-scrollspy.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-tab.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-tooltip.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-popover.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-button.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-collapse.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-carousel.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-typeahead.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/bootstrap-affix.js"></script>

    <script src="{{STATIC_URL}}/static/assets/js/holder/holder.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/google-code-prettify/prettify.js"></script>

    <script src="{{STATIC_URL}}/static/assets/js/application.js"></script>
    <script src="{{STATIC_URL}}/static/assets/js/jquery.js"></script>
    <script src="{{STATIC_URL}}/static/dist/js/bootstrap.min.js"></script>
    <!-- Placed at the end of the document so the pages load faster -->
    
  </body>
</html>



django_housingmap/templates/slider.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
	<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<script>
	$(function() {
		$( "#slider-range" ).slider({
			position: 'absolute',
			orientation: "vertical",
			range: true,
			min:1997,
			max:2013,
			step:1,
			values: [ 1997, 2013 ],
			slide: function( event, ui ) {
				$( "#amount" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] );
			}
		});
		$( "#amount" ).val( $( "#slider-range" ).slider( "values", 0 ) +
			" - " + $( "#slider-range" ).slider( "values", 1 ) );
	});

	</script>
</head>
<body>
    <div class="selector">
	<label for="amount">Range:</label>
	<input type="text" id="amount" style="border:0; color:#fffff; font-weight:bold;">
	<div id="slider-range" style="height:250px; left:50px"></div>
    </div>
</body>
</html>